[package]
name = "todo-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.28.1"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
itertools = "0.13.0"
unicode-width = "0.2.0"
color-eyre = "0.6.3"
crossterm = "0.28.1"
chrono = "0.4.38"